const decisionTypes = {
  WinDecision: "win_decision",
  LoseDecision: "lose_decision",
};

const PlaceTypes = {
  GoldPlace: "gold_place",
  SilverPlace: "silver_place",
  BronzePlace: "bronze_place",
};

const MedalTypes = {
  Gold: "Gold",
  Silver: "Silver",
  Bronze: "Bronze",
};

const PointTypes = {
  Gained: "gained",
  Skipped: "skipped",
};

const MetricActions = [
  { data: "Takedown Score", id: 11 },
  { data: "Offence Score", id: 12 },
  { data: "Defence Score", id: 13 },
  { data: "Durability Score", id: 14 },
];

const list_fighters = [
  "nihat zahid mammadli",
  "murad mammadov",
  "hasrat jafarov",
  "sanan suleymanov",
  "rafig huseynov",
  "islam abbasov",
  "arif niftullayev",
  "murat lokiayev",
  "sabah shariati",
  "beka kandelaki",
  "mariya stadnik",
  "gultakin shirinova",
  "ilona dydiak semkiv",
  "zhala aliyeva",
  "alyona kolesnik",
  "birgul soltanova",
  "elis manolova",
  "aliabbas rzazade",
  "haji aliyev",
  "ziraddin bayramov",
  "turan bayramov",
  "nurmaqomedov osman",
  "magomedkhan magomedov",
  "giorgi meshvildishvili",
  "zholaman sharshenbekov",
  "liguo cao",
  "mehdi seifollah mohsen nejad",
  "islomjon bakhramov",
  "luis alberto orta sanchez",
  "joni khetsuriani",
  "mihai radu mihut",
  "husiyuetu husiyuetu",
  "akzhol makhmudov",
  "alexandrin gutu",
  "sanana suleymanov",
  "kamal ameer bey",
  "ali cengiz",
  "david losonczi",
  "semen sergeevich novikov",
  "nursultan tursynov",
  "jalgasbay berdimuratov",
  "mohammadhadi saravi",
  "artur omarov",
  "gabriel alejandro rosillo kindelan",
  "artur aleksanyan",
  "tamas levai",
  "amin mohammadzaman mirzazadeh",
  "oscar pino hinds",
  "lingzhe meng",
  "riza kayaalp",
  "abdellatif mohamed ahmed mohamed",
  "wanhao zou",
  "stevan andria micic",
  "almaz smanbekov",
  "rei higuchi",
  "aman aman",
  "tulga tumur ochir",
  "sebastian c rivera",
  "iszmail muszukajev",
  "vazgen tevanyan",
  "rahman mousa amouzadkhalili",
  "kyle douglas dake",
  "zaurbek sidakov",
  "feng lu",
  "yones aliakbar emamichoghaei",
  "soner demirtas",
  "myles nazem amine",
  "azamat dauletkekov",
  "magomed sharipov",
  "javrail shapiev",
  "akhmed tazhudinov",
  "magomedkhan magomedovitch magomedov",
  "givi matcharashvili",
  "ibrahim ciftci",
  "amir hossein zare",
  "geno petriashvili",
  "daniel ligeti",
  "taha akgul",
  "mason mark parris",
  "victor ciobanu"
];


export { decisionTypes, MedalTypes, PlaceTypes, PointTypes, MetricActions, list_fighters };
