import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n.use(initReactI18next).init({
  debug: true,
  fallbackLng: "en",
  interpolation: {
    escapeValue: true,
  },
  resources: {
    en: {
      translation: {
        Country: "Country",
        Fighter: "Fighter",
        Years: "Years",
        "Search offence stats": "Search offence stats",
        "Search Country": "Search Country",
        "Search Fighter": "Search Fighter",
        "Inside the ring: Tactical Evaluation": "Inside the ring: Tactical Evaluation",
        "Career Summary": "Career Summary",
        "Overall score": "Overall score",
        "Scorecard metrics": "Scorecard metrics",
        "Summary stats": "Summary stats",
        Scores: "Scores",
        Medals: "Medals",
        "Score by weight": "Score by weight",
        "Score by level": "Score by level",
        "Scores by Years": "Scores by Years",
        "Win Rate": "Win Rate",
        "Win Decisions": "Win Decisions",
        "Lose Decisions": "Lose Decisions",
        Gold: "Gold",
        Bronze: "Bronze",
        Silver: "Silver",
        "No bronze medals": "No bronze medals",
        "No gold medals": "No gold medals",
        "No silver medals": "No silver medals",
        Won: "Won",
        "Number of fights": "Number of fights",
        Lost: "Lost",
        "Passivity per fight": "Passivity per fight",
        "Overall Scores by Years": "Overall Scores by Years",
        "Offence stats by Years": "Offence stats by Years",
        Lang: "Lang",
        "All Years": "All Years",
        // Points
        "Total (gained & skipped) points": "Total (gained & skipped) points",
        "Avg gained points": "Avg gained points",
        "Total gained points": "Total gained point",
        "Avg skipped points": "Avg skipped points",
        "Total skipped points": "Total skipped points",
        // Stats
        "Action escape rate": "Action escape rate",
        "Takedown escape rate": "Takedown escape rate",
        "Pin to parter escape rate": "Pin to parter escape rate",
        "Roll escape rate": "Roll escape rate",
        "Protection zone escape rate": "Protection zone escape rate",
        "Parterre escape rate": "Parterre escape rate",
        "Action skipped points per fight": "Action skipped points per fight",
        "Protection zone count per fight": "Protection zone count per fight",
        "Action point per fight": "Action point per fight",
        "Action count per fight": "Action count per fight ",
        "Action success rate": "Action success rate",
        "Protection zone points per fight": "Protection zone points per fight",
        "Roll success rate": "Roll success rate",
        "Roll points per fight": "Roll points per fight",
        "Parterre success rate": "Parterre success rate",
        "Takedown Success rate": "Takedown Success rate",
        "Takedown per fight total": "Takedown per fight total",
        "Takedown Count": "Takedown Count",
        "Single Leg takedown Success Rate": "Single Leg takedown success rate",
        "Single leg takedown count": "Single leg takedown count",
        "Average takedown points per fight": "Average takedown points per fight",
        "Double leg takedown counts": "Double leg takedown counts",
        "Double leg takedown success rate": "Double leg takedown success rate",
        //  Metrics
        "Takedown Score": "Takedown Score",
        "Offence Score": "Offence Score",
        "Durability Score": "Durability Score",
        "Offence Stats": "Offence Stats",
        "Defence Score": "Defence Score",
        "Action Success rate": "Action Success rate",
        "Action points per fight": "Action points per fight",
        "Parterre count per fight": "Parterre count per fight",
        "Parterre points per fight": "Parterre points per fight",
        "Protection zone success rate": "Protection zone success rate",
        "Roll count per fight": "Roll count per fight",
        "Takedown score 2nd part": "Takedown score 2nd part",
        "Defence Score 2nd part": "Defence Score 2nd part",
        "Offence Score 2nd part": "Offence Score 2nd part",
        "Total action counts per fight (2nd part)": "Total action counts per fight (2nd part)",
        "Total successful defenses per fight (2nd part)": "Total successful defenses per fight (2nd part)",
      },
    },
    aze: {
      translation: {
        Country: "Ölkə ",
        Fighter: "Güləşçi",
        Years: "İllər",
        "Inside the ring: Tactical Evaluation": "Güləş meydanında: Taktiki qiymətləndirmə",
        "Career Summary": "Karyera xülasəsi",
        "Overall score": "Ümumi xal",
        "Search Offence stats": "Hücum axtarışı",
        "Search Country": "Ölkə axtarışı",
        "Search Fighter": "Güləşçi axtarışı",
        "Scorecard metrics": "Hesab kartı metrikləri",
        "Summary stats": "Yekun statistika",
        Scores: "Xallar",
        Medals: "Medallar",
        "Score by weight": "Çəkiyə görə xallar",
        "Score by level": "Səviyyəyə görə xallar",
        "Scores by Years": "İllərə görə xallar",
        "Win Rate": "Qələbə faizi",
        "Win Decisions": "Qələbə qərarları",
        "Lose Decisions": "Məğlubiyyət qərarları",
        Gold: "Qızıl",
        Bronze: "Bürünc",
        Silver: "Gümüş",
        "No bronze medals": "Bürünc medallarsız",
        "No gold medals": "Qızıl medallarsız",
        "No silver medals": "Gümüş medallarsız",
        Won: "Qələbə sayı",
        Lang: "Dil",
        "All Years": "Bütün illər",
        "Number of fights": "Döyüş sayı",
        Lost: "Məğlubiyyət sayı",
        "Overall Scores by Years": "İllər üzrə ümumi xal",
        "Offence stats by Years": "İllər üzrə hücum statistikası",
        "Total (gained & skipped) points": "Cəmi (qazanılan və itirilən) xallar",
        "Avg gained points": "Qazanılan xalların orta sayı",
        "Total gained points": "Cəmi qazanılan xallar",
        "Avg skipped points": "İtirilən xalların orta sayı",
        "Total skipped points": "Cəmi itirilən xallar",
        "Passivity per fight": "Güləş zamanı passivlik",
        // Stats
        "Action escape rate": "Hərəkətdən uğurlu azad olunma faizi",
        "Takedown escape rate": "Ələ keçirmədən uğurlu azad olunma faizi",
        "Pin to parter escape rate": "Parterə düşmədən yayınma dərəcəsi",
        "Roll escape rate": "Uğurlu yuvarlanma faizi",
        "Protection zone escape rate": "Müdafiə zonasında uğurlu azad olunma faizi",
        "Parterre escape rate": "Parterdə uğurlu azad olunma dərəcəsi",
        "Action skipped points per fight": "Güləş zamanı hərəkət üçün itirilən xallar",
        "Protection zone count per fight": "Güləş zamanı müdafiə zonasının sayı",
        "Action point per fight": "Güləş zamanı hərəkət üçün xallar",
        "Action count per fight": "Güləş zamanı hərəkətlərin sayı",
        "Action success rate": "Uğurlu hərəkətlərin faizi",
        "Protection zone points per fight": "Döyüşdə müdafiə zonası üçün xallar",
        "Roll success rate": "Uğurlu yuvarlanma faizi",
        "Roll points per fight": "Yuvarlanma xalları",
        "Parterre success rate": "Parter vəziyyətində uğur faizi",
        "Takedown Success rate": "Uğurlu ələ keçirmə faizi",
        "Takedown per fight total": "Güləş zamanı ələ keçirmələrin sayı",
        "Takedown Count": "Ələ keçirmələrin ümumi sayı",
        "Single Leg takedown Success Rate": "Tək ayaqlı ələ keçirmə uğur faizi",
        "Single leg takedown count": "Tək ayaqlı ələ keçirmələrin sayı",
        "Average takedown points per fight": "Döyüş başına ələ keçirmə üçün orta xallar",
        "Double leg takedown counts": "İki ayaqlı ələ keçirmələrin sayı",
        "Double leg takedown success rate": "İki ayaqlı ələ keçirmə uğur faizi",
        // Metrics
        "Takedown Score": "Ələ keçirmə xalı",
        "Offence Score": "Hücum xalı",
        "Durability Score": "Davamlılıq xalı",
        "Offence Stats": "Hücum statistikası",
        "Defence Score": "Müdafiə xalı",
        "Action Success rate": "Hərəkətlərin uğurluluğu",
        "Action points per fight": "Döyüş başına hərəkət xalları",
        "Parterre count per fight": "Güləş zamanı parter sayı",
        "Parterre points per fight": "Güləş zamanı parter xalları",
        "Protection zone success rate": "Müdafiə zonasında uğurluluq",
        "Roll count per fight": "Güləş zamanı yuvarlanma sayı",
        "Takedown score 2nd part": "Ələ keçirmə xalı 2-ci hissə",
        "Defence Score 2nd part": "Müdafiə xalı 2-ci hissə",
        "Offence Score 2nd part": "Hücum xalı 2-ci hissə",
        "Total action counts per fight (2nd part)": "Güləş zamanı ümumi hərəkətlərin sayı 2-ci hissə",
        "Total successful defenses per fight (2nd part)": "Uğurlu müdafiə hərəkətlərinin sayı 2-ci hissə",
      },
    },
    ru: {
      translation: {
        Country: "Страна",
        Fighter: "Борец",
        Years: "Года",
        "Inside the ring: Tactical Evaluation": "Внутри ринга: Тактическая оценка",
        "Career Summary": "Сводка карьеры",
        "Overall score": "Общий балл",
        "Search Offence stats": "Поиск статистики атаки",
        "Search Fighter": "Поиск Борец",
        "Search Country": "Поиск Страна",
        "Scorecard metrics": "Метрики счетной карты",
        "Summary stats": "Сводная статистика",
        Scores: "Очки",
        Medals: "Медали",
        "Score by weight": "Очки по весу",
        "Score by level": "Очки по уровню",
        "Scores by Years": "Баллы по годам",
        "Win Rate": "Процент побед",
        "Win Decisions": "Решения о победе",
        "Lose Decisions": "Решения о проигрыше",
        Gold: "Золото",
        Bronze: "Бронза",
        Silver: "Серебро",
        Lang: "Язык",
        "All Years": "Все годы",
        "No bronze medals": "Без бронзовых медалей",
        "No gold medals": "Без бронзовых медалей",
        "No silver medals": "Без бронзовых медалей",
        Won: "Выиграно",
        "Number of fights": "Количество боев",
        Lost: "Количество проигранных боев",
        "Overall Scores by Years": "Общий балл по годам",
        "Offence stats by Years": "Статистика атаки по годам",
        "Total (gained & skipped) points": "Всего (набранные и пропущенные) очки",
        "Avg gained points": "Среднее количество набранных очков",
        "Total gained points": "Всего набранных очков",
        "Avg skipped points": "Среднее количество пропущенных очков",
        "Total skipped points": "Всего пропущенных очков",
        "Passivity per fight": "Пассивность за бой",
        // Stats
        "Action escape rate": "Процент успешных освобождений от действия",
        "Takedown escape rate": "Процент успешных освобождений от перехвата",
        "Pin to parter escape rate": "Процент успешных освобождений от прижима к партеру",
        "Roll escape rate": "Процент успешных перекатов",
        "Protection zone escape rate": "Процент успешных освобождений в зоне защиты",
        "Parterre escape rate": "Процент успешных освобождений в партере",
        "Action skipped points per fight": "Пропущенные очки за действие за бой",
        "Protection zone count per fight": "Количество в зоне защиты за бой",
        "Action point per fight": "Очки за действие за бой",
        "Action count per fight": "Количество действий за бой",
        "Action success rate": "Процент успешности действий",
        "Protection zone points per fight": "Очки в зоне защиты за бой",
        "Roll success rate": "Процент успешности перекатов",
        "Roll points per fight": "Очки за перекат за бой",
        "Parterre success rate": "Процент успешности в партере",
        "Takedown Success rate": "Процент успешности перехвата",
        "Takedown per fight total": "Всего перехватов за бой",
        "Takedown Count": "Количество перехватов",
        "Single Leg takedown Success Rate": "Процент успешности одноногого перехвата",
        "Single leg takedown count": "Количество одноногих перехватов",
        "Average takedown points per fight": "Среднее количество очков за перехват за бой",
        "Double leg takedown counts": "Количество двуногих перехватов",
        "Double leg takedown success rate": "Процент успешности двуногого перехвата",
        //  Metrics
        "Takedown Score": "Балл за перехват",
        "Offence Score": "Балл атаки",
        "Durability Score": "Балл устойчивости",
        "Offence Stats": "Статистика атаки",
        "Defence Score": "Балл защиты",
        "Action Success rate": "Успешность действий",
        "Action points per fight": "Очки за действия за бой",
        "Parterre count per fight": "Количество партеров за бой",
        "Parterre points per fight": "Очки за партер за бой",
        "Protection zone success rate": "Успешность в зоне защиты",
        "Roll count per fight": "Количество перекатов за бой",
        "Takedown score 2nd part": "Балл за перехват 2-ая часть",
        "Defence Score 2nd part": "Балл защиты 2-ая часть",
        "Offence Score 2nd part": "Балл атаки 2-ая часть",
        "Total action counts per fight (2nd part)": "Количество действий за 2-ую часть боя",
        "Total successful defenses per fight (2nd part)": "Количество успешных защитных действий за 2-ую часть боя",
      },
    },
  },
});

export default i18n;
